"""Native carousel controls, pagination, looping, autoplay and layouts."""
import importlib.util
import time
import re
from pathlib import Path
spec = importlib.util.spec_from_file_location('smoke', Path(__file__).with_name('android-smoke.py'))
ui = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ui)
ui.adb('shell', 'am', 'force-stop', ui.PACKAGE)
ui.adb('shell', 'am', 'start', '-n', ui.PACKAGE + '/.MainActivity')
time.sleep(4)
ui.tap('Ajustes')
ui.tap('Ver componentes')
ui.tap('Buscar componentes')
ui.adb('shell', 'input', 'text', 'Carousel')
ui.adb('shell', 'input', 'keyevent', '66')
ui.tap('Siguiente diapositiva', scroll=True)
ui.find('2 / 3')
ui.tap('Ir a diapositiva 3')
ui.find('3 / 3')
assert ui.find('Siguiente diapositiva', clickable=True).get('enabled') == 'false'
ui.tap('Ir a diapositiva 1')
ui.find('1 / 3')
ui.tap('Reproducir carrusel')
time.sleep(3.5)
ui.tap('Pausar carrusel')
nodes = ui.nodes()
count = next(n.get('text') for n in nodes if n.get('text') in ['2 / 3', '3 / 3'])
time.sleep(3.5)
ui.find(count)
# Bring the settings back into view without leaving the carousel.
ui.adb('shell', 'input', 'swipe', '540', '650', '540', '1650', '350')
ui.tap('Repetir en bucle')
ui.tap('Ir a diapositiva 3', scroll=True)
ui.tap('Siguiente diapositiva')
ui.find('1 / 3')
ui.tap('Ir a diapositiva 3')
dot = ui.find('Ir a diapositiva 3')
_, top, _, _ = map(int, re.findall(r'\d+', dot.get('bounds')))
ui.adb('shell', 'input', 'swipe', '820', str(top - 250), '260', str(top - 250), '400')
ui.find('1 / 3')
ui.adb('shell', 'input', 'swipe', '540', '650', '540', '1650', '350')
ui.tap('Presentación del carrusel')
ui.tap('Dos tarjetas')
ui.find('Gasas estériles', scroll=True)
ui.find('Termómetro digital')
ui.adb('shell', 'input', 'swipe', '540', '650', '540', '1650', '350')
ui.tap('Presentación del carrusel')
ui.tap('Vertical')
ui.tap('Siguiente diapositiva', scroll=True)
ui.find('2 / 3')
print('OK: navigation, dots, boundaries, autoplay/pause, loop, two cards and vertical.')
